### ISSUE TITLE
How to upload a Video on D.Tube by API

### ISSUE THREAD

**Issue by alvaroseparovich** [skzap/javalon#7]
There is a example of POST request In the readme.md, but it is so general:
```
var newTx = {
    type: javalon.TransactionType.FOLLOW,
    data: {
        target: 'bob'
    }
}

newTx = javalon.sign(alice_key, 'alice', newTx)
``` 
this is a example of request to follow some user, and the model of payload required is there, but I want to record a video on de block-chain, then I need to know the right TransactionType and payload.
how could I get this information?

**Comment by techcoderx** [comment]
The tx type for new videos is 4 (`javalon.TransactionType.COMMENT` without burn) or type 13 (`javalon.TransactionType. PROMOTED_COMMENT` with burn).

The tx data should contain `link` (string) which is the permalink of the new video, `json` for video metadata, `vt` (integer) for the VP amount to be spent on the first vote and `tag` (string) for the first tag associated with the first vote. Tx type 13 contains an additional field called `burn` (integer) that specifies the number of **0.01 DTUBE** to be burnt for promotion (to burn 1 DTUBE this will be `100`). 4,400 VP is added to the first vote for every DTUBE burned.

You can have a look at the example transaction for one of the videos with both IPFS and Skynet mirrors [here](https://blocks.oneloved.tube/#/tx/6ecf896a5510b4023fb193ddf089ee1fefd226197f22977e7a02a16805ae5ab8).

**Comment by alvaroseparovich** [comment]
@techcoderx THANK YOU BRO
I was trying to find the answer only looking the other repositories and understanding the code... but to receive the answer so fast and painless is really Nice.

**Comment by alvaroseparovich** [comment]
Sorry man,
I had noticed that the link of the video is not auto generated. In the example of the request you sent, the link of the video is the same as the ipfs's src link.
Is there some good practice about it to pay attention?

**Comment by techcoderx** [comment]
The permalink can be anything that does not exist already, but usually it is the source video hash. Using the same permalink edits existing content instead of creating a new one.
